# Generated by Django 4.0.5 on 2022-06-18 23:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pushup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AlterField(
            model_name='pushupday',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 6, 18, 23, 18, 43, 651151, tzinfo=utc)),
        ),
    ]
