# Generated by Django 4.0.5 on 2022-06-18 21:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pushup', '0002_alter_pushupday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushupday',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 6, 18, 21, 8, 7, 361956, tzinfo=utc)),
        ),
    ]
