# Generated by Django 4.0.5 on 2022-06-18 21:22

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pushup', '0003_alter_pushupday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushupday',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='pushupday',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 6, 18, 21, 22, 29, 690679, tzinfo=utc)),
        ),
    ]
