# Generated by Django 4.0.5 on 2022-06-18 23:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pushup', '0003_profile_age_alter_pushupday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pushupday',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 6, 18, 23, 22, 44, 841963, tzinfo=utc)),
        ),
    ]
